### PR TITLE
🐛 Fix for #118 using command instead of shell module

### PR DESCRIPTION
**Pull request by bbaassssiiee**
ansible-vault/tasks/main.yml:19 -name: Check Vault installation

### CODE REVIEW

**Comment by brianshumate** [comment]
Thanks!

**Comment by jpiron** [comment]
@bbaassssiiee what OS do you use ?

Does it work when you run your playbook twice ?

On Ubuntu, `command` is a shell builtin and requires the shell module to work properly. 
I get a `No such file or directory` error with the command module.

**Comment by bbaassssiiee** [comment]
I'm on RHEL7 and Centos7.

**Comment by bbaassssiiee** [comment]
```

changed: [vaultserver] => changed=true
  cmd:
  - command
  - -v
  - vault
  delta: '0:00:00.004380'
  end: '2020-01-29 13:00:48.906283'
  rc: 0
  start: '2020-01-29 13:00:48.901903'
  stderr: ''
  stderr_lines: <omitted>
  stdout: /usr/bin/vault
  stdout_lines: <omitted>
```

**Comment by bbaassssiiee** [comment]
```
sh-4.2# ls -l /bin/sh
lrwxrwxrwx. 1 root root 4 Nov  4 14:30 /bin/sh -> bash
```

**Comment by bbaassssiiee** [comment]
https://github.com/ansible/ansible-lint/blob/master/lib/ansiblelint/rules/UseCommandInsteadOfShellRule.py

**Comment by jpiron** [comment]
I am still having the issue : 

```
TASK [ansible-vault : Check Vault installation] ***************************************************************************************************************************************************************************************************************
task path: /path/roles/ansible-vault/tasks/main.yml:33
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "master:/home/user/.local/lib/python3.5/site-packages/ansible/module_utils/basic.py", line 2592, in run_command
    cmd = subprocess.Popen(args, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
fatal: [consul-vault-01]: FAILED! => {
    "changed": false,
    "cmd": "command -v vault",
    "invocation": {
        "module_args": {
            "_raw_params": "command -v vault",
            "_uses_shell": false,
            "argv": null,
            "chdir": null,
            "creates": null,
            "executable": null,
            "removes": null,
            "stdin": null,
            "stdin_add_newline": true,
            "strip_empty_ends": true,
            "warn": true
        }
    },
    "msg": "[Errno 2] No such file or directory",
    "rc": 2
}
...ignoring
```

```
$ ansible --version
ansible 2.9.6
  config file = /path/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/.local/lib/python3.5/site-packages/ansible
  executable location = /home/user/.local/bin/ansible
  python version = 3.5.2 (default, Oct  8 2019, 13:06:37) [GCC 5.4.0 20160609]
```

The target OS is Ubuntu 16.04.6 LTS

**Pull request merged**
