### PR TITLE
feat(init) add vault init ability

### PR DESCRIPTION
**Pull request by eagleusb**
Add the ability to initialize Vault (cluster) when needed, it's a preview as I'll implement the output of unseal keys and the root token properly.

### CODE REVIEW

**Review by bbaassssiiee — CHANGES_REQUESTED** [review]
Secret-zero (operator init output) is not stored securely. Better implement this in a separate (project) role.

**Comment by bbaassssiiee** [comment]
Maybe this inspires? https://github.com/dockpack/keybase_unseal

**Comment by eagleusb** [comment]
Thanks for the inpu @bbaassssiiee . I'll add support for keybase and eventually GPG key for initialization.
To be honest I don't see how it will be more secured in another role, or copied from the table output manually.

The person deploying Vault with `ansible-vault` will (and want) initialize it, usually just copying the table output for unseal keys and root token. It would be a minimum to have that feature in `ansible-vault` IMO.

**Comment by bbaassssiiee** [comment]
Not everything needs to go in one role. For comparison https://github.com/dockpack/vault_dojo uses this role and an couple of others to initialize vault create policies. Most of these thing depend on the organization using Vault, hence my objection to implement initialization in this role. This role is already quite complex.

Shamir secret sharing is one of the foundations of Vault. If you initialize and get unencrypted unseal keys, then that violates that principle.

**Comment by eagleusb** [comment]
I know composition and it's a good engineering principle.

However the promise of `ansible-vault` is to deploy a Vault machine,cluster. Thus it has Raft, Consul... backends support and also auto-unsealing. 

There is a dependency error while you don't even support initialization, which is a necessary step for these. It's also an engineering principle violation, but I won't fight for it, as you said the role is quite complex and needs a refactorization.

Thanks for your time,
Regards

**Pull request closed without merging**
