### PR TITLE
distro: add support for Flatcar Linux

### PR DESCRIPTION
**Pull request by ahjohannessen**
- make dotfile name configurable
   and possible to opt out of dotfile
   creation.

 - make systemd unit path configurable as
   some distros have /lib/systemd/system
   readonly.

- add Flatcar.yml to vars folder with
   appropriate distro settings.

- add `_vault_nix_distros` list with
   supported *nix distributions.

### CODE REVIEW

**Comment by ahjohannessen** [comment]
@bbaassssiiee  WDYT? The changes are similar to what I did for Flatcar Linux support in ansible-consul.

**Review by bbaassssiiee — CHANGES_REQUESTED** [review]
Please define `_vault_nix_distros` in `vars/main.yml`.

**Comment by ahjohannessen** [comment]
@bbaassssiiee updated the PR and defined `_vault_nix_distros` in `vars/main.yml`.

**Review by bbaassssiiee — APPROVED** [review]

**Comment by bbaassssiiee** [comment]
> @bbaassssiiee WDYT? The changes are similar to what I did for Flatcar Linux support in ansible-consul.

Convention, `vars/main.yml` is a common place to have such.

**Comment by ahjohannessen** [comment]
@bbaassssiiee Fixed new-line lint error

**Comment by ahjohannessen** [comment]
@bbaassssiiee Not sure what this is from:

```
  DEBUG    Using selector: EpollSelector
  Error: [new-line-at-end-of-file] no new line character at the end of file
  ```

**Comment by bbaassssiiee** [comment]
Both vars/main.yml and vars/Flatcar.yml need
a newline at end of file.

**Comment by ahjohannessen** [comment]
@bbaassssiiee I have updated with newlines.

**Comment by ahjohannessen** [comment]
@bbaassssiiee Sorry for all the noise. Installed yamllint and verified locally for newline. Hopefully, no CI errors now.

**Comment by bbaassssiiee** [comment]
Thanks!

**Pull request merged**
