### PR TITLE
Add optional proxy variables for the server to use

### PR DESCRIPTION
**Pull request by kvonbredow**
This PR aims to allow the user to specify a proxy configuration which gets put into the vault server's service definition.  These are all optional and by default there are no environment variables set.

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
What is the problem that this PR is supposed to solve?

**Comment by kvonbredow** [comment]
In deployments which do not have direct internet access, this enables you to still use a cloud KMS to unseal your vault via a proxy.  Sorry for not explaining that in the initial description.

**Comment by bbaassssiiee** [comment]
Please resolve the conflicts

**Comment by kvonbredow** [comment]
@bbaassssiiee Is this a feature that could still be merged?  Happy to make any adjustments to get this included

**Review by bbaassssiiee — APPROVED** [review]
Looks OK to me.

**Pull request merged**
