### PR TITLE
Revert "feat: add acme plugin"

### PR DESCRIPTION
**Pull request by bbaassssiiee**
Reverts ansible-community/ansible-vault#316

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
Going for the generic plugin PR

**Comment by gardar** [comment]
@bbaassssiiee I think there might be some confusion here.

PR #313 is to be able to install plugins, which opens up the possibility of adding plugins in the future.
#316 was to add the first plugin, the acme plugin.

I was looking to install the acme plugin and decided to split it up into two PR's, since the role didn't support installing plugins at all.

With that being said... Can we get this revert reverted? 😃

**Comment by bbaassssiiee** [comment]
Sorry, this pull request couldn’t be reverted automatically. It may have already been reverted, or the content may have changed since it was merged.

**Comment by bbaassssiiee** [comment]
I'm too busy now, would you create a PR?

**Comment by gardar** [comment]
@bbaassssiiee sure thing: #319

**Pull request merged**
