### PR TITLE
Enhanced file permission hardening

### PR DESCRIPTION
**Pull request by lakrass**
- more strict file permissions for existing paths
- implemented some missing file perm hardenings
- implemented deletion of unused files when installing Vault via repo
- use private folder for tls keys when hardening is enabled

Perms are based on HashiCorps hardening guide: https://developer.hashicorp.com/vault/docs/concepts/production-hardening

### CODE REVIEW

**Comment by lakrass** [comment]
This PR is ready for review!

**Comment by lakrass** [comment]
fixes #265

**Comment by FalcoSuessgott** [comment]
can u rebase please

**Comment by FalcoSuessgott** [comment]
Squash and add a Conventional commit and then we can merge :)
https://www.conventionalcommits.org/en/v1.0.0/

**Comment by lakrass** [comment]
I messed up my rebase on the first run. I rebuilt my branch on top of the master by squashing & cherry-picking and switched to conventional commits.

This should hopefully now be mergeable :)

**Pull request merged**
