### PR TITLE
Add vault listener on localhost

### PR DESCRIPTION
**Pull request by patsevanton**
Add vault listener on localhost

`vault_listener_localhost_enable: True` - i can change to `False`

### CODE REVIEW

**Comment by patsevanton** [comment]
Export VAULT_ADDR
`export VAULT_ADDR=http://127.0.0.1:8200`

Status
```
vault status
Key                Value
---                -----
Seal Type          shamir
Initialized        false
Sealed             true
Total Shares       0
Threshold          0
Unseal Progress    0/0
Unseal Nonce       n/a
Version            n/a
HA Enabled         true
```
vault initialization
```
vault operator init
Unseal Key 1: KZCI64eonfyqXkT2Og5IDBl+U38yMK/MLHbCqVW8HCCP
Unseal Key 2: 8Gtz7eLBAOLCqdnjx4yYdBN1kK1bK6vCYy+SIrXt0jJ1
Unseal Key 3: wLVl8FSs/q8V7B5mDUxr/Q7VFe6z1KVt2XcxZg1Ds0db
Unseal Key 4: +0EnSzz8iMNcdhOpin2a5DRHOLLtkqMkQgR3ekOysVW/
Unseal Key 5: FExBJnnhIl90xeQIcNWasIW1WnHK3PKjXW5vrfn5hIig

Initial Root Token: s.kLn8gHaruepmD6iXcCASg95p

Vault initialized with 5 key shares and a key threshold of 3. Please securely
distribute the key shares printed above. When the Vault is re-sealed,
restarted, or stopped, you must supply at least 3 of these keys to unseal it
before it can start servicing requests.

Vault does not store the generated master key. Without at least 3 key to
reconstruct the master key, Vault will remain permanently sealed!

It is possible to generate new unseal keys, provided you have a quorum of
existing unseal keys shares. See "vault operator rekey" for more information.
```

**Comment by patsevanton** [comment]
```
root@vault1:~# vault --version
Vault v1.5.5 (f5d1ddb3750e7c28e25036e1ef26a4c02379fc01)
```

**Review by bbaassssiiee — CHANGES_REQUESTED** [review]
Please use `false` as a default, and take care to use lowecase booleans.

**Comment by bbaassssiiee** [comment]
Fix for #143

**Comment by patsevanton** [comment]
I changed. May be will change readme.md ?

**Comment by bbaassssiiee** [comment]
Excellent idea to change the README.md.

**Comment by patsevanton** [comment]
Add vault_listener_localhost_enable in readme.md

**Comment by patsevanton** [comment]
Please review PR

**Comment by patsevanton** [comment]
Please review PR

**Review by bbaassssiiee — APPROVED** [review]

**Pull request merged**
