### PR TITLE
Fix enterprise install

### PR DESCRIPTION
**Pull request by FalcoSuessgott**
Hashicorp renamed its enterprise pkgs to `+ent.hsm` and `+ent` (https://releases.hashicorp.com/vault/)

this PR adjusts the role accordingly

Furthermore:
	* actually download the checksum file from hashicorp CDN
	* allow enterprise installation via apt or dnf repo
 	* update README.md
	* bump default vault version to `1.8.4`

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
Thanks!

**Comment by bbaassssiiee** [comment]
Any volunteers to test this?

**Comment by FalcoSuessgott** [comment]
I could test this via molecule. The auto unseal PR would be tough tho. Any ideas on how to the test multiple playbooks with molecule?

**Comment by bbaassssiiee** [comment]
> I could test this via molecule. The auto unseal PR would be tough tho. Any ideas on hoe to the test multiple playbooks with molecule?

[dockpack.base_redis]( https://github.com/dockpack/base_redis/tree/master/molecule/default) could give you some ideas for testing with Molecule.

**Comment by boldandbusted** [comment]
I'd love to help get this into main. If I am looking at the existing Molecule-oriented code in the main repo, would 'testing' this just include adding new relevant tests in `molecule/default/molecule.yml`? Do we have a high-level idea of what would qualify as good tests?

**Comment by FalcoSuessgott** [comment]
Howdy @bbaassssiiee & @boldandbusted,

I have rebased this PR against master branch and I really want to get this merged soon. I have tested this role for another client seems to work great. I was wondering how we could test this PR since this is an enterprise feature and requires us to have a license?

**Comment by bbaassssiiee** [comment]
Please fix to have checks passing

**Review by bbaassssiiee — CHANGES_REQUESTED** [review]
Please amend until checks pass

**Comment by FalcoSuessgott** [comment]
Yes will do. I will quickly test this for ubuntu/debian based systems today

**Comment by FalcoSuessgott** [comment]
blocked until #321 is merged.

@brianshumate or @bbaassssiiee any chance on merging #321. so I can proceed with other PRs?

**Comment by bbaassssiiee** [comment]
#321 has been merged. Brian is no longer involved.

**Comment by FalcoSuessgott** [comment]
> #321 has been merged. Brian is no longer involved.

If you need help maintaing that project I would like to volunteer also my company would probably contribute an enterprise testing licence if needed

**Comment by FalcoSuessgott** [comment]
enterprise install is so far ready, tests are failing for now due to the lack of an enterprise license. I will so what I can do. The idea is it to store the license in github secrets and use the env lookup plugin.

**Pull request closed without merging**
